package com.choimanseon.pocketlog.ui

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.*
import androidx.compose.ui.graphics.vector.ImageVector

/** [com.choimanseon.pocketlog.data.Category.icon] keys, in the order the icon picker shows them. */
val CategoryIcons: Map<String, ImageVector> = linkedMapOf(
    "rice_bowl" to Icons.Rounded.RiceBowl,
    "restaurant" to Icons.Rounded.Restaurant,
    "dinner" to Icons.Rounded.DinnerDining,
    "fastfood" to Icons.Rounded.Fastfood,
    "egg" to Icons.Rounded.Egg,
    "cookie" to Icons.Rounded.Cookie,
    "bakery" to Icons.Rounded.BakeryDining,
    "cafe" to Icons.Rounded.LocalCafe,
    "bar" to Icons.Rounded.SportsBar,
    "wine" to Icons.Rounded.WineBar,
    "delivery" to Icons.Rounded.DeliveryDining,
    "convenience" to Icons.Rounded.LocalConvenienceStore,
    "grocery" to Icons.Rounded.ShoppingBasket,
    "cart" to Icons.Rounded.ShoppingCart,
    "bag" to Icons.Rounded.ShoppingBag,
    "clothes" to Icons.Rounded.Checkroom,
    "laptop" to Icons.Rounded.Laptop,
    "phone" to Icons.Rounded.Smartphone,
    "chair" to Icons.Rounded.Chair,
    "kitchen" to Icons.Rounded.Kitchen,
    "soap" to Icons.Rounded.Soap,
    "home" to Icons.Rounded.Home,
    "laundry" to Icons.Rounded.LocalLaundryService,
    "handyman" to Icons.Rounded.Handyman,
    "bolt" to Icons.Rounded.Bolt,
    "water" to Icons.Rounded.WaterDrop,
    "receipt" to Icons.Rounded.ReceiptLong,
    "subway" to Icons.Rounded.Subway,
    "bus" to Icons.Rounded.DirectionsBus,
    "taxi" to Icons.Rounded.LocalTaxi,
    "train" to Icons.Rounded.Train,
    "flight" to Icons.Rounded.Flight,
    "bike" to Icons.Rounded.DirectionsBike,
    "car" to Icons.Rounded.DirectionsCar,
    "gas" to Icons.Rounded.LocalGasStation,
    "car_repair" to Icons.Rounded.CarRepair,
    "parking" to Icons.Rounded.LocalParking,
    "medication" to Icons.Rounded.Medication,
    "hospital" to Icons.Rounded.LocalHospital,
    "run" to Icons.Rounded.DirectionsRun,
    "fitness" to Icons.Rounded.FitnessCenter,
    "movie" to Icons.Rounded.Movie,
    "ticket" to Icons.Rounded.ConfirmationNumber,
    "game" to Icons.Rounded.SportsEsports,
    "music" to Icons.Rounded.MusicNote,
    "book" to Icons.Rounded.MenuBook,
    "palette" to Icons.Rounded.Palette,
    "casino" to Icons.Rounded.Casino,
    "tv" to Icons.Rounded.LiveTv,
    "subscriptions" to Icons.Rounded.Subscriptions,
    "code" to Icons.Rounded.Code,
    "cloud" to Icons.Rounded.Cloud,
    "cut" to Icons.Rounded.ContentCut,
    "brush" to Icons.Rounded.Brush,
    "spa" to Icons.Rounded.Spa,
    "school" to Icons.Rounded.School,
    "child" to Icons.Rounded.ChildCare,
    "toys" to Icons.Rounded.Toys,
    "pets" to Icons.Rounded.Pets,
    "gift" to Icons.Rounded.CardGiftcard,
    "redeem" to Icons.Rounded.Redeem,
    "flower" to Icons.Rounded.LocalFlorist,
    "celebration" to Icons.Rounded.Celebration,
    "groups" to Icons.Rounded.Groups,
    "handshake" to Icons.Rounded.Handshake,
    "work" to Icons.Rounded.Work,
    "payments" to Icons.Rounded.Payments,
    "savings" to Icons.Rounded.Savings,
    "bank" to Icons.Rounded.AccountBalance,
    "chart" to Icons.Rounded.ShowChart,
    "shield" to Icons.Rounded.Shield,
    "sell" to Icons.Rounded.Sell,
    "box" to Icons.Rounded.Inventory2,
    "more" to Icons.Rounded.MoreHoriz,
)

fun categoryIcon(key: String?): ImageVector = key?.let(CategoryIcons::get) ?: Icons.Rounded.ReceiptLong
